# Generated by Django 4.2.4 on 2023-09-01 19:29

import AppCoder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_entregable_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.TimeField(null=True, verbose_name=AppCoder.models.Curso),
        ),
    ]
