# Generated by Django 4.2.4 on 2023-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_profesor_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
    ]
