# Generated by Django 4.2.4 on 2023-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_curso_options_alter_curso_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='AppCoder.curso'),
        ),
    ]
